name: DevOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compilando el proyecto
        run: echo "Construyendo el sitio web..."

  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Reportando estado del build
        run: echo "El build ha sido completado con éxito."

  deploy:
    runs-on: ubuntu-latest
    needs: report-build-status
    steps:
      - name: Subir artefactos de la página
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Desplegar en GitHub Pages
        uses: actions/deploy-pages@v4
